CREATE DATABASE movix;

USE movix;

CREATE TABLE usuarios (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(150) NOT NULL DEFAULT '',
    email VARCHAR(150) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL,
    cpf VARCHAR(14) NOT NULL UNIQUE,
    telefone VARCHAR(20) NOT NULL,
    perfil VARCHAR(30) NOT NULL DEFAULT 'Operador',
    status VARCHAR(20) NOT NULL DEFAULT 'Ativo'
);